
# ####################################
# NodeApp AREA
# ####################################
electron: electron-quick-start electron-api-demos zh-cn-Electron-API-Demos electron-manka
electron-quick-start:
	https://github.com/electron/$@
electron-api-demos:
	https://github.com/electron/$@
zh-cn-Electron-API-Demos:
	git clone https://github.com/fuchao2012/$@
electron-manka:
	git clone https://github.com/xu455255849/Electron-manka electron-manka


# ####################################
# Utils AREA
# ####################################
clean:
	find . -type d -name "node_modules" -exec rm -rvf {} \;
