
include ./00-env.mk


# ####################################
# net-tools AREA
# ####################################
include ./net-tools/socat.mk
include ./net-tools/nc.mk
include ./net-tools/misc.mk


# ####################################
# ds micro service AREA
# ####################################
# 分布式及微服务
include ./ds/micro.mk
include ./ds/consul.mk
include ./ds/misc.mk


# ####################################
# Utils AREA
# ####################################

