install:
	bower install;


# ####################################
# Init AREA
# ####################################
init: deps
	bower init
deps:
	cnpm install -g bower


# ####################################
# Demo AREA
# ####################################
demo-add:
	bower install fancybox --save
	bower install bootstrap --save
	bower install jquery --save
	bower install https://github.com/sbstjn/timesheet.js.git --save


# ####################################
# Utils AREA
# ####################################
clean:
	rm -rvf bower_components
