.PHONY: clean


# ####################################
# Dashboard AREA
# ####################################
all:
	make -C test


# ####################################
# Utils AREA
# ####################################
clean:
	make -C test clean
	rm -rvf *.o
