# Generated by Django 2.2.3 on 2019-07-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190713_1241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuildInType',
            new_name='BuiltInType',
        ),
        migrations.AlterModelTable(
            name='builtintype',
            table='builtin_type',
        ),
    ]
