# Generated by Django 2.2.3 on 2019-07-14 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190713_1250'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='builtintype',
            table='misc_builtin_type',
        ),
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='说明')),
                ('pid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.AddressInfo', verbose_name='自关联')),
            ],
            options={
                'verbose_name': '省市县地址信息',
                'verbose_name_plural': '省市县地址信息',
                'db_table': 'misc_address',
                'unique_together': {('address', 'note')},
            },
        ),
    ]
