.PHONY: all clean


# ####################################
# Dashboard AREA
# ####################################
all:
	make -C thinkjs all
	make -C thinkjs mult


# ####################################
# Utils AREA
# ####################################
clean:
	make -C thinkjs clean
